spring:
    datasource:
        url: jdbc:mysql://localhost:3333/employee_db?useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
    application:
        name: EMPLOYMENT-SERVICE
server:
    port: 8052
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8090/eureka/